services:
  - type: web
    name: shophub-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishing:
      - source: "../Frontend/dist"
        target: "/static"
